version: '3'

services:
    database:
        build:
            context: database
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "3333:3306"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./database/data:/var/lib/mysql

    php-fpm:
        build:
            context: php-fpm
        depends_on:
            - database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
        volumes:
            - ../app:/var/www

    nginx:
        build:
            context: nginx
        volumes:
            - ../app:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        depends_on:
            - php-fpm
        ports:
            - "8090:80"

    rabbitmq:
        image: rabbitmq:3.8.9-alpine
#        working_dir: /app
#        hostname: rabbit-mq
#        container_name: 'rabbit-mq'
        ports:
            - '15672:15672'
            - '5672:5672'
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
            RABBITMQ_DEFAULT_VHOST: my_vhost