fos_rest:
    serializer:
        serialize_null: false
    param_fetcher_listener: true
    allowed_methods_listener: true
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, priorities: ['json'], fallback_format: json }
    routing_loader: false
    body_listener: true